<?php

return [
    'newsletter.confirmation' => [
        'name' => 'Newsletter subscription confirmation',
        'subject' => 'Welcome to {{app_name}} updates',
        'variables' => ['app_name'],
        'body_html' => '<h2>Subscription confirmed</h2><p>Thank you for subscribing to {{app_name}} updates. We will send useful lending news and financial tips to this address.</p>',
        'body_text' => "Subscription confirmed\n\nThank you for subscribing to {{app_name}} updates. We will send useful lending news and financial tips to this address.",
    ],
    'newsletter.admin' => [
        'name' => 'New newsletter subscriber',
        'subject' => 'New newsletter subscriber: {{email}}',
        'variables' => ['email'],
        'body_html' => '<h2>New newsletter subscriber</h2><p><strong>Email:</strong> {{email}}</p>',
        'body_text' => "New newsletter subscriber\n\nEmail: {{email}}",
    ],
    'consultation.admin' => [
        'name' => 'New consultation request',
        'subject' => 'New consultation request from {{full_name}}',
        'variables' => ['full_name', 'email', 'phone', 'preferred_date', 'preferred_time', 'message'],
        'body_html' => '<h2>New consultation request</h2><p><strong>Name:</strong> {{full_name}}<br><strong>Email:</strong> {{email}}<br><strong>Phone:</strong> {{phone}}<br><strong>Preferred time:</strong> {{preferred_date}} at {{preferred_time}}</p><p><strong>Message:</strong><br>{{message}}</p>',
        'body_text' => "New consultation request\n\nName: {{full_name}}\nEmail: {{email}}\nPhone: {{phone}}\nPreferred time: {{preferred_date}} at {{preferred_time}}\nMessage: {{message}}",
    ],
    'consultation.confirmation' => [
        'name' => 'Consultation confirmation',
        'subject' => 'We received your consultation request',
        'variables' => ['first_name', 'preferred_date', 'preferred_time'],
        'body_html' => '<h2>Thank you, {{first_name}}</h2><p>We received your consultation request for <strong>{{preferred_date}} at {{preferred_time}}</strong>. Our team will contact you soon to confirm the appointment.</p>',
        'body_text' => "Thank you, {{first_name}}\n\nWe received your consultation request for {{preferred_date}} at {{preferred_time}}. Our team will contact you soon to confirm the appointment.",
    ],
    'loan_application.admin' => [
        'name' => 'New loan application',
        'subject' => 'New loan application from {{full_name}}',
        'variables' => ['full_name', 'email', 'phone', 'company', 'business_type', 'loan_amount', 'loan_purpose', 'timeline', 'message'],
        'body_html' => '<h2>New loan application</h2><p><strong>Name:</strong> {{full_name}}<br><strong>Email:</strong> {{email}}<br><strong>Phone:</strong> {{phone}}<br><strong>Company:</strong> {{company}}</p><p><strong>Business type:</strong> {{business_type}}<br><strong>Requested amount:</strong> {{loan_amount}}<br><strong>Purpose:</strong> {{loan_purpose}}<br><strong>Timeline:</strong> {{timeline}}</p><p><strong>Message:</strong><br>{{message}}</p>',
        'body_text' => "New loan application\n\nName: {{full_name}}\nEmail: {{email}}\nPhone: {{phone}}\nCompany: {{company}}\nBusiness type: {{business_type}}\nRequested amount: {{loan_amount}}\nPurpose: {{loan_purpose}}\nTimeline: {{timeline}}\nMessage: {{message}}",
    ],
    'loan_application.confirmation' => [
        'name' => 'Loan application confirmation',
        'subject' => 'Your loan application has been received',
        'variables' => ['full_name', 'loan_amount', 'loan_purpose'],
        'body_html' => '<h2>Thank you, {{full_name}}</h2><p>We received your application for <strong>{{loan_amount}}</strong> for {{loan_purpose}}. Our team will review it and contact you within 24 hours.</p>',
        'body_text' => "Thank you, {{full_name}}\n\nWe received your application for {{loan_amount}} for {{loan_purpose}}. Our team will review it and contact you within 24 hours.",
    ],
    'auth.registration_verification' => [
        'name' => 'Registration email verification',
        'subject' => 'Verify your {{app_name}} email address',
        'variables' => ['first_name', 'action_url'],
        'body_html' => '<h2>Welcome, {{first_name}}</h2><p>Please verify your email address to activate your account.</p>',
        'body_text' => "Welcome, {{first_name}}\n\nPlease verify your email address to activate your account:\n{{action_url}}",
    ],
    'auth.welcome' => [
        'name' => 'Welcome after verification',
        'subject' => 'Welcome to {{app_name}}',
        'variables' => ['first_name'],
        'body_html' => '<h2>Your account is active</h2><p>Welcome to {{app_name}}, {{first_name}}. Your email address has been verified successfully.</p>',
        'body_text' => "Your account is active\n\nWelcome to {{app_name}}, {{first_name}}. Your email address has been verified successfully.",
    ],
    'auth.password_reset' => [
        'name' => 'Password reset link',
        'subject' => 'Reset your {{app_name}} password',
        'variables' => ['first_name', 'action_url'],
        'body_html' => '<h2>Password reset request</h2><p>Hello {{first_name}}, use the button below to reset your password. If you did not request this, no action is required.</p>',
        'body_text' => "Password reset request\n\nHello {{first_name}}, reset your password using this link:\n{{action_url}}\n\nIf you did not request this, no action is required.",
    ],
    'auth.two_factor_code' => [
        'name' => 'Two-factor login code',
        'subject' => 'Your {{app_name}} login code',
        'variables' => ['first_name', 'code', 'expires_in'],
        'body_html' => '<h2>Login verification code</h2><p>Hello {{first_name}}, your one-time login code is:</p><p style="font-size:30px;font-weight:800;letter-spacing:8px">{{code}}</p><p>This code expires in {{expires_in}} minutes.</p>',
        'body_text' => "Login verification code\n\nHello {{first_name}}, your one-time login code is {{code}}. It expires in {{expires_in}} minutes.",
    ],
    'auth.login_activity' => [
        'name' => 'Successful login activity',
        'subject' => 'New login to your {{app_name}} account',
        'variables' => ['first_name', 'ip_address', 'user_agent', 'logged_in_at'],
        'body_html' => '<h2>New login detected</h2><p>Hello {{first_name}}, your account was accessed at {{logged_in_at}}.</p><p><strong>IP address:</strong> {{ip_address}}<br><strong>Device:</strong> {{user_agent}}</p>',
        'body_text' => "New login detected\n\nHello {{first_name}}, your account was accessed at {{logged_in_at}}.\nIP address: {{ip_address}}\nDevice: {{user_agent}}",
    ],
    'auth.account_locked' => [
        'name' => 'Account lockout alert',
        'subject' => 'Security alert: your account has been locked',
        'variables' => ['first_name', 'ip_address', 'action_url'],
        'body_html' => '<h2>Account locked</h2><p>Hello {{first_name}}, your account was locked after repeated failed login attempts from {{ip_address}}. Reset your password to recover access.</p>',
        'body_text' => "Account locked\n\nHello {{first_name}}, your account was locked after repeated failed login attempts from {{ip_address}}. Reset your password here:\n{{action_url}}",
    ],
    'auth.account_recovered' => [
        'name' => 'Account recovery notification',
        'subject' => 'Your {{app_name}} account has been recovered',
        'variables' => ['first_name'],
        'body_html' => '<h2>Account access restored</h2><p>Hello {{first_name}}, your account lock has been cleared. You can sign in again.</p>',
        'body_text' => "Account access restored\n\nHello {{first_name}}, your account lock has been cleared. You can sign in again.",
    ],
    'auth.password_changed' => [
        'name' => 'Password changed confirmation',
        'subject' => 'Your {{app_name}} password was changed',
        'variables' => ['first_name', 'changed_at'],
        'body_html' => '<h2>Password changed</h2><p>Hello {{first_name}}, your password was changed at {{changed_at}}. Contact support immediately if this was not you.</p>',
        'body_text' => "Password changed\n\nHello {{first_name}}, your password was changed at {{changed_at}}. Contact support immediately if this was not you.",
    ],
    'auth.profile_updated' => [
        'name' => 'Profile update notification',
        'subject' => 'Your {{app_name}} profile was updated',
        'variables' => ['first_name', 'changed_at'],
        'body_html' => '<h2>Profile updated</h2><p>Hello {{first_name}}, your profile was updated at {{changed_at}}. Contact support if you did not make this change.</p>',
        'body_text' => "Profile updated\n\nHello {{first_name}}, your profile was updated at {{changed_at}}. Contact support if you did not make this change.",
    ],
    'auth.email_change_verification' => [
        'name' => 'Email change verification',
        'subject' => 'Confirm your new {{app_name}} email address',
        'variables' => ['first_name', 'action_url'],
        'body_html' => '<h2>Confirm your new email address</h2><p>Hello {{first_name}}, use the button below to confirm this address for your account.</p>',
        'body_text' => "Confirm your new email address\n\nHello {{first_name}}, confirm this address using the following link:\n{{action_url}}",
    ],
    'auth.account_status' => [
        'name' => 'Account activation or deactivation',
        'subject' => 'Your {{app_name}} account status changed',
        'variables' => ['first_name', 'status'],
        'body_html' => '<h2>Account status changed</h2><p>Hello {{first_name}}, your account status is now <strong>{{status}}</strong>.</p>',
        'body_text' => "Account status changed\n\nHello {{first_name}}, your account status is now {{status}}.",
    ],
    'email.test' => [
        'name' => 'Test email',
        'subject' => '{{app_name}} email test',
        'variables' => ['app_name'],
        'body_html' => '<h2>Email configuration test</h2><p>Your {{app_name}} email configuration is working.</p>',
        'body_text' => "Email configuration test\n\nYour {{app_name}} email configuration is working.",
    ],
    'notification.generic' => [
        'name' => 'General administrator notification',
        'subject' => '{{subject}}',
        'variables' => ['full_name', 'message', 'subject'],
        'body_html' => '<h2>Hello {{full_name}}</h2><p>{{message}}</p>',
        'body_text' => "Hello {{full_name}}\n\n{{message}}",
    ],
];
